name: Update Manga Cache

on:
  schedule:
    - cron: ''  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests supabase

      - name: Run update script
        run: python update_cache.py

      - name: Check Git status
        run: git status  # Debugging: Shows if changes exist

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes
        run: |
          git add manga_cache.json
          git diff --cached --quiet || (git commit -m "Updated manga_cache.json" && git push)
        continue-on-error: true
